### ISSUE TITLE
Netflix issue

### ISSUE THREAD

**Issue by JustArchi** [ArchiDroid/android_device_samsung_i9300#121]
Apparently it's not working (you don't say!)

Wishlist for now.

**Comment by JustArchi** [comment]
TODO: Test this later -> https://github.com/TeamBliss-Devices/android_device_samsung_smdk4412-common/commit/5e38fa90325bae3fea234217de114560e4566d91

**Comment by JustArchi** [comment]
Done.

**Comment by will1b** [comment]
I know this is supposed to be fixed, but Netflix still doesn't work for me as of build 15. It gets stuck loading, and if you try and exit it, it makes all other video applications (tested YouTube, MX Player and Gallery) also get stuck loading (not even getting metadata on the file length) until the phone is rebooted (both regular and soft reboot work). I can live without it if it can't be fixed, but it'd still be nice to be able to consume legal streaming content on my phone.

What sort of logs should I capture to help you replicate this, and how should I go about it?

**Comment by JustArchi** [comment]
Won't fix, I have no interest in this bug.

**Comment by will1b** [comment]
Might be worth reopening it just on the offchance that someone else wants to come in and fix it up? I mean, it's unlikely but might be worth a go.

**Comment by JustArchi** [comment]
Sure why not.
